.TH SADL 1 "December 2024" "v1.0.0" "Sadl Command Manual"
.SH NAME
sadl \- SaltyDownloader which downloads things
.SH SYNOPSIS
.B sadl
[\fIoptions\fR] \fIinput-file\fR
.SH DESCRIPTION
Sadl is a command-line utility for downloading things in bulk.
.SH OPTIONS
.TP
.B -I, --instagram
Input file containing a list of Instagram URLs to download.
.TP
.B --version
Show the version of the application.
.TP
.B --help
Display help information.
.TP
.B --update
Updates app.
.SH EXAMPLES
.B sadl -I insta.txt
Download Instagram Reels from the URLs listed in insta.txt.
.SH AUTHOR
Cooper D'Andilly
